<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Location;
class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        

        $location = new Location;
        $location->name = 'A&C Mall';
        $location->save();
        $location = new Location;
        $location->name = 'Achimota';
        $location->save();
        $location = new Location;
        $location->name = 'Achimota School';
        $location->save();
        $location = new Location;
        $location->name = 'Ada College of Education';
        $location->save();
        $location = new Location;
        $location->name = 'Adabraka';
        $location->save();
        $location = new Location;
        $location->name = 'Airport City Accra';
        $location->save();
        $location = new Location;
        $location->name = 'Adom FM';
        $location->save();
        $location = new Location;
        $location->name = 'Airport Residential Area';
        $location->save();
        $location = new Location;
        $location->name = 'Akweteyman';
        $location->save();
        $location = new Location;
        $location->name = 'Alajo';
        $location->save();
        $location = new Location;
        $location->name = 'Apenkwa';
        $location->save();
        $location = new Location;
        $location->name = 'Asaase Radio';
        $location->save();
        $location = new Location;
        $location->name = 'Asempa FM';
        $location->save();
        $location = new Location;
        $location->name = 'Asaase Radio';
        $location->save();
        $location = new Location;
        $location->name = 'Asempa FM';
        $location->save();
       

        $location = new Location;
        $location->name = 'Ashaiman Senior High School';
        $location->save();
        $location = new Location;
        $location->name = ' Chemu Senior High School';
        $location->save();
        $location = new Location;
        $location->name = ' Christian Methodist Senior High School';
        $location->save();
        $location = new Location;
        $location->name = ' Christian Village';
        $location->save();
        $location = new Location;
        $location->name = 'Citi FM (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = ' Christian Village';
        $location->save();
        $location = new Location;
        $location->name = 'CitiTrends (radio show)';
        $location->save();
 
        $location = new Location;
        $location->name = 'Dangme District';
        $location->save();
        $location = new Location;
        $location->name = ' Darkuman';
        $location->save();
        $location = new Location;
        $location->name = 'Dawhenya';
        $location->save();
        $location = new Location;
        $location->name = '   Template:Districts of Greater Accra';
        $location->save();
        $location = new Location;
        $location->name = ' Dreams F.C. (Ghana)';
        $location->save();

        $location = new Location;
        $location->name = 'Fantasy coffin';
        $location->save();
        $location = new Location;
        $location->name = 'Figurative palanquin';
        $location->save();

        $location = new Location;
        $location->name = '  Fort Kongenstein';
        $location->save();
        $location = new Location;
        $location->name = 'Fox FM Ghana';
        $location->save();
        $location = new Location;
        $location->name = 'Frafraha';
        $location->save();

        $location = new Location;
        $location->name = 'Ga Central Municipal District';
        $location->save();
        $location = new Location;
        $location->name = 'Ga District';
        $location->save();
        $location = new Location;
        $location->name = ' Ga East Municipal District';
        $location->save();
        $location = new Location;
        $location->name = ' Ga North Municipal District';
        $location->save();
        $location = new Location;
        $location->name = 'Ga West Municipal District';
        $location->save();
        $location = new Location;
        $location->name = ' Ghana-Lebanon Islamic School';
        $location->save();

        $location = new Location;
        $location->name = 'Happy FM (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = ' Hitz FM';
        $location->save();
        $location = new Location;
        $location->name = 'Joy FM (Ghana)';
        $location->save();

        $location = new Location;
        $location->name = 'Kasapa FM';
        $location->save();
        $location = new Location;
        $location->name = 'Kisseman';
        $location->save();
        $location = new Location;
        $location->name = 'Kofi Annan International Peacekeeping Training Centre';
        $location->save();
        $location = new Location;
        $location->name = 'Kokomlemle';
        $location->save();
        $location = new Location;
        $location->name = 'Kotobabi';
        $location->save();
        $location = new Location;
        $location->name = 'Kpledjoo Festival';
        $location->save();
        $location = new Location;
        $location->name = 'Kwashieman';
        $location->save();

        $location = new Location;
        $location->name = ' La Nkwantanang Madina Municipal District';
        $location->save();
        $location = new Location;
        $location->name = 'Lapaz (Accra)';
        $location->save();
        $location = new Location;
        $location->name = 'Lartebiokorshie';
        $location->save();
        $location = new Location;
        $location->name = 'Laterbiokorshie';
        $location->save();
        $location = new Location;
        $location->name = 'Live FM';
        $location->save();


        $location = new Location;
        $location->name = '  Mamprobi';
        $location->save();
        $location = new Location;
        $location->name = 'Mataheko';
        $location->save();
        $location = new Location;
        $location->name = '  Nii Boi Town';
        $location->save();
        $location = new Location;
        $location->name = 'Nmai Dzorn';
        $location->save();
        $location = new Location;
        $location->name = 'Nungua Senior High School';
        $location->save();
        $location = new Location;
        $location->name = 'Reilly Senior High School';
        $location->save();
        $location = new Location;
        $location->name = 'Obonu FM';
        $location->save();
        $location = new Location;
        $location->name = 'Odorgonno Senior High School';
        $location->save();
        $location = new Location;
        $location->name = ' Odorkor';
        $location->save();
        $location = new Location;
        $location->name = 'Pig Farm (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = 'Parish of St Sylvanus, Pokuase';
        $location->save();
        $location = new Location;
        $location->name = 'Radio 1 (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = ' Radio 2 (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = 'Radio Gold';
        $location->save();
        $location = new Location;
        $location->name = 'St Martin de Porres School (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = 'St Marys Senior High School (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = 'St. Thomas Aquinas Senior High School';
        $location->save();
        $location = new Location;
        $location->name = 'Sakaman';
        $location->save();
        $location = new Location;
        $location->name = 'Starr FM (Ghana)';
        $location->save();
        $location = new Location;
        $location->name = 'Tema Fishing Harbour';
        $location->save();
        $location = new Location;
        $location->name = 'The Trust Hospital';
        $location->save();
        $location = new Location;
        $location->name = 'Uncle T FC';
        $location->save();
        $location = new Location;
        $location->name = 'Uniiq FM';
        $location->save();
        $location = new Location;
        $location->name = 'University of Ghana Primary School Legon';
        $location->save();
        $location = new Location;
        $location->name = 'Vision 1 FM';
        $location->save();
        $location = new Location;
        $location->name = 'Weija Dam';
        $location->save();
        $location = new Location;
        $location->name = 'Weija Gbawe Municipal District';
        $location->save();
        $location = new Location;
        $location->name = 'Uncle T FC';
        $location->save();
        $location = new Location;
        $location->name = 'West Africa Senior High School';
        $location->save();
        $location = new Location;
        $location->name = 'Uncle T FC';
        $location->save();
        $location = new Location;
        $location->name = 'Uniiq FM';
        $location->save();
        $location = new Location;
        $location->name = 'University of Ghana Primary School Legon';
        $location->save();
        $location = new Location;
        $location->name = 'Vision 1 FM';
        $location->save();
        $location = new Location;
        $location->name = 'Weija Dam';
        $location->save();
        $location = new Location;
        $location->name = 'Weija Gbawe Municipal District';
        $location->save();
        $location = new Location;
        $location->name = 'Uncle T FC';
        $location->save();
        $location = new Location;
        $location->name = 'West Africa Senior High School';
        $location->save();
       
    }
}
